import type { DesignDocument } from "./designDocument";

export const designDocumentFixtures = [
  {
    units: "in",
    face: {
      width: 24,
      height: 12,
      depth: 4,
      shape: "serpentine_top",
      material: "bahama_blue_granite",
      finish: "polished_face_pitched_sides",
    },
    elements: [
      {
        id: "el_name",
        type: "text",
        field: "name",
        content: "MARGARET A. HOLLOWAY",
        font: "memorial_serif_1",
        size_in: 1.25,
        x_in: 12,
        y_in: 3,
        rotation_deg: 0,
        align: "center",
        direction: "auto",
      },
      {
        id: "el_dates",
        type: "text",
        field: "dates",
        content: "1947 - 2026",
        font: "memorial_block_1",
        size_in: 0.8,
        x_in: 12,
        y_in: 5.1,
        rotation_deg: 0,
        align: "center",
        direction: "auto",
      },
      {
        id: "el_symbol",
        type: "symbol",
        asset_id: "sym_rose_01",
        x_in: 12,
        y_in: 7,
        rotation_deg: 0,
        scale: 1,
      },
    ],
    guides: {
      safe_margin_in: 0.75,
    },
  },
  {
    units: "in",
    face: {
      width: 16,
      height: 8,
      depth: 2,
      shape: "flat_grass_marker",
      material: "jet_black_granite",
      finish: "polished",
    },
    elements: [
      {
        id: "el_name",
        type: "text",
        field: "name",
        content: "ROBERT J. LEWIS",
        font: "memorial_serif_1",
        size_in: 0.95,
        x_in: 8,
        y_in: 2.1,
        rotation_deg: 0,
        align: "center",
        direction: "auto",
      },
      {
        id: "el_etch",
        type: "photo_etch",
        asset_url: "s3://headstone-assets/photo-etch/robert-lewis.jpg",
        shape: "oval",
        width_in: 2.5,
        height_in: 3.2,
        x_in: 8,
        y_in: 4.3,
        rotation_deg: 0,
      },
    ],
    guides: {
      safe_margin_in: 0.5,
      grid_step_in: 0.25,
    },
  },
  {
    units: "in",
    face: {
      width: 20,
      height: 10,
      depth: 3,
      shape: "upright_serpentine_top",
      material: "rose_pink_granite",
      finish: "polished_face",
    },
    elements: [
      {
        id: "el_hebrew",
        type: "text",
        field: "name",
        content: "שרה בת אברהם",
        font: "memorial_serif_1",
        size_in: 1,
        x_in: 10,
        y_in: 2.6,
        rotation_deg: 0,
        align: "center",
        direction: "rtl",
      },
      {
        id: "el_english",
        type: "text",
        field: "epitaph",
        content: "Beloved Mother and Grandmother",
        font: "memorial_script_1",
        size_in: 0.75,
        x_in: 10,
        y_in: 4.8,
        rotation_deg: 0,
        align: "center",
        direction: "auto",
      },
      {
        id: "el_dates",
        type: "text",
        field: "dates",
        content: "1939 - 2024",
        font: "memorial_block_1",
        size_in: 0.7,
        x_in: 10,
        y_in: 6.1,
        rotation_deg: 0,
        align: "center",
        direction: "auto",
      },
    ],
    guides: {
      safe_margin_in: 0.6,
    },
  },
  {
    units: "in",
    face: {
      width: 14,
      height: 14,
      depth: 3,
      shape: "heart",
      material: "limestone",
      finish: "sandblasted",
    },
    elements: [
      {
        id: "el_name",
        type: "text",
        field: "name",
        content: "BELLA",
        font: "memorial_script_1",
        size_in: 1.5,
        x_in: 7,
        y_in: 3.1,
        rotation_deg: 0,
        align: "center",
        direction: "auto",
      },
      {
        id: "el_custom_art",
        type: "custom_art",
        asset_url: "s3://headstone-assets/custom-art/paw-print.svg",
        format: "svg",
        width_in: 2.2,
        height_in: 2.2,
        x_in: 7,
        y_in: 6.2,
        rotation_deg: 0,
        manual_review_approved: true,
      },
    ],
    guides: {
      safe_margin_in: 0.5,
    },
  },
] satisfies DesignDocument[];
